In [1]:
import pandas as pd

In [4]:
identified_table = pd.read_csv('test/data/identified/EMX1_identifiedOfftargets.txt', sep='\t', index_col=False)

In [5]:
identified_table

,#BED Chromosome,BED Min.Position,BED Max.Position,BED Name,Filename,WindowIndex,Chromosome,Position,Sequence,+.mi,...,Length,BED off-target Chromosome,BED off-target start,BED off-target end,BED off-target name,BED Score,Strand,Cells,Targetsite,Target Sequence
0,chr15:44108746-44110769,1007,1025,chr15:44108746-44110769_1017_189,EMX1.sam,1,15:44108746-44110769,1017,GTAGACAAGAGTCTAAGCAGAAGAAGAAGAGAGCCACTACCCAACC...,116,...,23.0,chr15:44108746-44110769,1000.0,1023.0,chr15:44108746-44110769_1017_189,1.0,+,EMX_site1,EMX1,GAGTCCGAGCAGAAGAAGAANGG
1,chr1:236259170-236261754,1465,1486,chr1:236259170-236261754_1486_7,EMX1.sam,8,1:236259170-236261754,1486,ATGGAGCAGGCGACCAGGGGTGACTCAGAATGGAGCAGGTGACCAG...,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EMX_site1,EMX1,GAGTCCGAGCAGAAGAAGAANGG
2,chr1:236259170-236261754,1531,1539,chr1:236259170-236261754_1531_5,EMX1.sam,10,1:236259170-236261754,1531,GGGGTGACTCAGAATGGAGCAGGTGACCAGGGGAATAGACGTTAAC...,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EMX_site1,EMX1,GAGTCCGAGCAGAAGAAGAANGG
3,chr2:73159981-73162004,1008,1024,chr2:73159981-73162004_1017_489,EMX1.sam,12,2:73159981-73162004,1017,AAGGGCCTGAGTCCGAGCAGAAGAAGAAGGGCTCCCATCACATCAA...,243,...,23.0,chr2:73159981-73162004,1000.0,1023.0,chr2:73159981-73162004_1017_489,1.0,+,EMX_site1,EMX1,GAGTCCGAGCAGAAGAAGAANGG
4,chr3:197899267-197901348,1075,1081,chr3:197899267-197901348_1080_10,EMX1.sam,16,3:197899267-197901348,1080,TTAGGGTTAGGGTTAGGGTTAGGGTTCGGGTTTAGGGTTCAGGTTT...,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,EMX_site1,EMX1,GAGTCCGAGCAGAAGAAGAANGG
5,chr6:9117792-9119815,1007,1007,chr6:9117792-9119815_1007_4,EMX1.sam,18,6:9117792-9119815,1007,ATGTCCTCAGAGTTCTGTCCATTCTTCTTCTGCTCAGACGTTTTGT...,1,...,23.0,chr6:9117792-9119815,1000.0,1023.0,chr6:9117792-9119815_1007_4,1.0,-,EMX_site1,EMX1,GAGTCCGAGCAGAAGAAGAANGG

In [7]:
on_targets = identified_table[identified_table['Mismatches'] == 0]
off_targets = identified_table[identified_table['Mismatches'] > 0]
cleavage_sites = pd.concat([on_targets, off_targets])

In [38]:
for i, site in cleavage_sites.iterrows():
    print(site['#BED Chromosome'])

chr2:73159981-73162004
chr15:44108746-44110769
chr6:9117792-9119815

In [12]:
annotations = pd.read_csv('test/reporting/data/tmp/EMX1-10nm_annotation.bed',sep='\t', index_col=False, header=None)
annotations.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,chr15,44108746,44110769,chr15:44108746-44110769_1017_189,chr15,HAVANA,gene,44096690,44117000,.,-,.,"gene_id ""ENSG00000140259.6""; transcript_id ""EN...",0
1,chr15,44108746,44110769,chr15:44108746-44110769_1017_189,chr15,HAVANA,transcript,44096690,44117000,.,-,.,"gene_id ""ENSG00000140259.6""; transcript_id ""EN...",0
2,chr15,44108746,44110769,chr15:44108746-44110769_1017_189,chr15,HAVANA,CDS,44109427,44109646,.,-,2,"gene_id ""ENSG00000140259.6""; transcript_id ""EN...",0
3,chr15,44108746,44110769,chr15:44108746-44110769_1017_189,chr15,HAVANA,exon,44109427,44109646,.,-,.,"gene_id ""ENSG00000140259.6""; transcript_id ""EN...",0
4,chr2,73159981,73162004,chr2:73159981-73162004_1017_489,chr2,HAVANA,gene,73143389,73162020,.,+,.,"gene_id ""ENSG00000135638.9""; transcript_id ""EN...",0

In [17]:
a = 'chr15:44108746-44110769_1017_189'

In [68]:
b = annotations[3] == a
c = annotations[6] == 'gene'
d = annotations[b & c]
d.head(1)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,chr15,44108746,44110769,chr15:44108746-44110769_1017_189,chr15,HAVANA,gene,44096690,44117000,.,-,.,"gene_id ""ENSG00000140259.6""; transcript_id ""EN...",0

In [61]:
d.get_value(0,1)

44108746